//
// Created by evggenshch on 02.08.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTLOCATION_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTLOCATION_H

class trvComponentLocation {

};

#endif //EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTLOCATION_H
