//
// Created by evggenshch on 14.08.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTRESOURCEREQUIRMENT_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTRESOURCEREQUIRMENT_H



class trvComponentResourceRequirment {

};



#endif //EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTRESOURCEREQUIRMENT_H
