//
// Created by evggenshch on 14.08.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTENEMYATTACKRANGE_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTENEMYATTACKRANGE_H

class trvComponentEnemyAttackRange {
 private:
  int range;
};

#endif //EVGENIJ_SCHERBAKOV_GAME_TRVCOMPONENTENEMYATTACKRANGE_H
