//
// Created by evggenshch on 30.07.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVENTITYMATERIAL_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVENTITYMATERIAL_H

class trvComponentMaterial {
 private:

};

#endif //EVGENIJ_SCHERBAKOV_GAME_TRVENTITYMATERIAL_H
