//
// Created by evggenshch on 30.07.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVENTITYRESOURCEDOMAIN_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVENTITYRESOURCEDOMAIN_H

class trvEntityResourceDomain {

};

#endif //EVGENIJ_SCHERBAKOV_GAME_TRVENTITYRESOURCEDOMAIN_H
