//
// Created by evggenshch on 27.07.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVENTITYACTIONMENU_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVENTITYACTIONMENU_H

class trvEntityActionMenu {

};

#endif //EVGENIJ_SCHERBAKOV_GAME_TRVENTITYACTIONMENU_H
