//
// Created by evggenshch on 02.08.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMBUILDING_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMBUILDING_H

class trvSystemBuilding {

};

#endif //EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMBUILDING_H
