//
// Created by evggenshch on 16.08.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMENTITYCOLLISION_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMENTITYCOLLISION_H

class trvSystemEntityCollision {

};

#endif //EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMENTITYCOLLISION_H



///   std::distance