//
// Created by evggenshch on 30.07.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMENEMYAI_H
#define EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMENEMYAI_H

class trvSystemEnemyAI {

};

#endif //EVGENIJ_SCHERBAKOV_GAME_TRVSYSTEMENEMYAI_H
