//
// Created by evggenshch on 26.07.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_GCONTAINER_H
#define EVGENIJ_SCHERBAKOV_GAME_GCONTAINER_H

class gContainer {

};

#endif //EVGENIJ_SCHERBAKOV_GAME_GCONTAINER_H
