//
// Created by evggenshch on 26.07.18.
//

#ifndef EVGENIJ_SCHERBAKOV_GAME_GMOUSEEVENTSHANDLER_H
#define EVGENIJ_SCHERBAKOV_GAME_GMOUSEEVENTSHANDLER_H

class gMouseEventsHandler {
  bool ifPointIsClicked();
};

#endif //EVGENIJ_SCHERBAKOV_GAME_GMOUSEEVENTSHANDLER_H
